### [C]reate user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "adam@eduweb.pl",
  "password": "1234",
  "confirmPassword": "1234"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "adam@eduweb.pl",
  "password": "1234"
}

### Refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

### Logout
GET http://localhost:3000/auth/logout

### Delete
DELETE http://localhost:3000/auth/delete
