### [C]reate dishes
POST http://localhost:3000/dishes
Content-Type: application/json
Authorization

{
  "name": "1My supper Broccoli",
  "description": "...",
  "servings": 1
}

### [R]ead dishes
GET http://localhost:3000/dishes

### [R]ead one dish
GET http://localhost:3000/dishes/1

### [U]pdate dish
PATCH http://localhost:3000/dishes/5
Content-Type: application/json

{
  "name": "TEST"
}

### [D]elete dish
DELETE http://localhost:3000/dishes/190


### Sample exception
GET http://localhost:3000/dishes/exception


