### [C]reate ingredient
POST http://localhost:3000/ingredients
Content-Type: application/json

{
  "amount": 25,
  "dishId": 20,
  "productId": 1
}

### [R]ead ingredient
GET http://localhost:3000/ingredients/6
