version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dishes
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pa55w0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "5090:8080"

volumes:
  postgres_data:
